################## AUTH ##################
POST {{host}}/{{locale}}/api/restaurants/v1/login
Accept: application/json
Content-Type: application/json

{
    "email": "owner@trytiptop.app",
    "password": "secret"
}

### log out
POST {{host}}/{{locale}}/api/restaurants/v1/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{tokenRestaurant}}
