################## CITIES ##################
# Get all cities
GET {{host}}/{{locale}}/spa/countries/225/regions/50/cities
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### create city
GET {{host}}/{{locale}}/spa/countries/225/regions/50/cities/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### Store
POST {{host}}/{{locale}}/spa/countries/225/regions/50/cities
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "country_id": 225,
  "region_id": 80,
  "timezone_id": 5,
  "english_name": "TEST",
  "population": 300000,
  "latitude": 43.48257618,
  "longitude": 97.39059283,
  "translations": {
    "en": {
      "name": "name",
      "description": "description",
      "slug": "slug"
    },
    "ar": {
      "name": "سوسو",
      "description": "كيكي",
      "slug": "بابا"
    }
  }
}

###

### Edit city
GET {{host}}/{{locale}}/spa/countries/225/regions/50/cities/70/edit
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

###THESE DON'T WORK YET
### Update city
PATCH {{host}}/{{locale}}/spa/countries/42/regions/50/cities/1180
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "country_id": 50,
  "region_id": 20,
  "timezone_id": 8,
  "english_name": "TEST2",
  "population": 500000,
  "latitude": 12.48257618,
  "longitude": 56.39059283,
  "translations": {
    "en": {
      "name": "name2",
      "description": "description2",
      "slug": "slug2"
    },
    "ar": {
      "name": "سوسو2",
      "description": "كيكي2",
      "slug": "2بابا"
    }
  }
}

###

### delete city
DELETE {{host}}/{{locale}}/spa/countries/225/regions/50/cities/1181
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
