################## CURRENCIES ##################
# Get all available Currencies
GET {{host}}/{{locale}}/spa/currencies
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

### create currency
GET {{host}}/{{locale}}/spa/currencies/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Store
POST {{host}}/{{locale}}/spa/currencies
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "english_name": "currency name",
    "code": "CN",
    "symbol": "&",
    "rate": 0.1357810,
    "decimal_separator": ".",
    "thousands_separator": ",",
    "is_symbol_after": 1,
    "status": 1
}

###

### Edit currency
GET {{host}}/{{locale}}/spa/currencies/54/edit
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###


### Update currency
PATCH {{host}}/{{locale}}/spa/currencies/59
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "english_name": "currency name2",
    "code": "CB",
    "symbol": "?",
    "rate": 0.09452530,
    "decimal_separator": ",",
    "thousands_separator": ".",
    "is_symbol_after": 1,
    "status": 1
}

###

### delete currency
DELETE {{host}}/{{locale}}/spa/currencies/58
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
