################## LANGUAGES ##################
# Get all available Languages
GET {{host}}/{{locale}}/spa/languages
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

### create language
GET {{host}}/{{locale}}/spa/languages/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Store
POST {{host}}/{{locale}}/spa/languages
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "translations": {
        "en": {
            "name": "Store Title"
        },
        "ar": {
            "name": "سوسو"
        }
    },
    "english_name": "language name",
    "code": "ff",
    "locale_country": "test",
    "is_rtl": 1,
    "status": 1
}

###

### Edit language
GET {{host}}/{{locale}}/spa/languages/65/edit
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###


### Update language
PATCH {{host}}/{{locale}}/spa/languages/65
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "translations": {
        "en": {
            "name": "Update Title"
        },
        "ar": {
            "name": "بابا"
        }
    },
    "english_name": "language name2",
    "code": "fe",
    "locale_country": "test2",
    "is_rtl": 1,
    "status": 1
}

###

### delete language
DELETE {{host}}/{{locale}}/spa/languages/63
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
