################## Order/Checkout ##################
### Get checkout info
GET {{host}}/{{locale}}/api/v1/orders/checkout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Get previous orders
GET {{host}}/{{locale}}/api/v1/orders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
