################## BLOG ##################
### blog posts index
GET {{host}}/{{locale}}/api/v1/blog
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### blog posts show
GET {{host}}/{{locale}}/api/v1/blog/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

################## PRIVACY ##################
### privacy show
GET {{host}}/{{locale}}/api/v1/privacy
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

################## FAQ ##################
### faq index
GET {{host}}/{{locale}}/api/v1/faqs
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


# This one makes no sense but I'm keeping it
### faq show
GET {{host}}/{{locale}}/api/v1/faqs/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
