################## PREFERENCES ##################
# Get all preferences
GET {{host}}/{{locale}}/spa/preferences
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### Store
POST {{host}}/{{locale}}/spa/preferences
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ar": {
    "app_title": null,
    "app_description": null,
    "contact_mobile": null,
    "contact_phone": null,
    "contact_phone_whatsApp": null,
    "contact_email": null,
    "address": null,
    "social_media_facebook": null,
    "social_media_instagram": null,
    "social_media_linkedin": null,
    "social_media_twitter": null,
    "google_site_verification": null,
    "google_analytics": null,
    "sms_verification_content": null,
    "mobile_app_needs_approval_message": null,
    "mobile_app_account_is_suspended": null
  },
  "en": {
    "app_title": "Test title",
    "app_description": "test",
    "contact_mobile": null,
    "contact_phone": null,
    "contact_phone_whatsApp": null,
    "contact_email": "test@domain.com",
    "address": null,
    "social_media_facebook": null,
    "social_media_instagram": null,
    "social_media_linkedin": null,
    "social_media_twitter": null,
    "google_site_verification": null,
    "google_analytics": null,
    "sms_verification_content": "Hello and Welcome here is your code %code%",
    "mobile_app_needs_approval_message": "Hi %name%, welcome your account is not approved yet, please check back soon :)",
    "mobile_app_account_is_suspended": "Dear %name%, your account is suspended @_@"
  }
}

###

