################## PRODUCT ##################
### products index
GET {{host}}/{{locale}}/api/v1/categories/2/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
