################## REGIONS ##################
# Get all regions
GET {{host}}/{{locale}}/spa/countries/225/regions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### create region
GET {{host}}/{{locale}}/spa/countries/225/regions/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### Store
POST {{host}}/{{locale}}/spa/countries/225/regions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "country_id": 12,
  "english_name": "TEST",
  "code": 1,
  "translations": {
    "en": {
      "name": "name",
      "slug": "slug"
    },
    "ar": {
      "name": "سوسو",
      "slug": "بابا"
    }
  }
}

###

### Edit region
GET {{host}}/{{locale}}/spa/countries/225/regions/81/edit
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

###THESE DON'T WORK YET
### Update region
PATCH {{host}}/{{locale}}/spa/countries/42/regions/81
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "country_id": 14,
  "english_name": "TEST2",
  "code": 2,
  "translations": {
    "en": {
      "name": "name2",
      "slug": "slug2"
    },
    "ar": {
      "name": "2سوسو",
      "slug": "بابا2"
    }
  }
}

###

### delete region
DELETE {{host}}/{{locale}}/spa/countries/225/regions/83
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
