################## Misc ##################

### boot
GET {{host}}/{{locale}}/api/v1/boot
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "platform": "iOS",
    "build_number": 251
}

### home
GET {{host}}/{{locale}}/api/v1/home
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "latitude": 36.20339842006327,
    "longitude": 44.00734072932359,
    "channel": "grocery",
    "selected_address_id": 1
}

### products
GET {{host}}/{{locale}}/api/v1/categories/2/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}



// Todo: This not should be /register, it should be /complete-profile, First change it as code then here.
### register
POST {{host}}/{{locale}}/api/v1/register
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "New User",
    "email": "new-user@trytiptop.app",
    "phone_number": "5555555555",
    "phone_country_code": "964",
    "locale": "en",
    "region_id": 2,
    "city_id": 1
}

### faqs
GET {{host}}/{{locale}}/api/v1/faqs
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### faq
GET {{host}}/{{locale}}/api/v1/faqs/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### privacy
GET {{host}}/{{locale}}/api/v1/privacy
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### log
POST {{host}}/{{locale}}/api/v1/logs/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "data": "idk"
}

### Edit profile
POST {{host}}/{{locale}}/api/v1/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "new user2",
    "email": "new-user2@trytiptop.com",
    "phone_number": "5555555556",
    "phone_country_code": "964",
    "dob": "1994-06-16",
    "gender": "Male",
    "locale": "en"
}
