################## TAXONOMIES ##################
### Types of Taxonomies
# Get all available types for taxonomies
GET {{host}}/{{locale}}/spa/taxonomies/types
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Taxonomies ?type=category
GET {{host}}/{{locale}}/spa/taxonomies?type=category
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

### create taxonomy ?type=category
GET {{host}}/{{locale}}/spa/taxonomies/create?type=category
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Store
POST {{host}}/{{locale}}/spa/taxonomies
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "translations": {
    "en": {
      "title": "Test Title",
      "description": "asd asd asd"
    },
    "ar": {
      "title": "واو",
      "description": "ما ما في"
    }
  },
  "parentId": 5,
  "icon": "f6d5 fas fa-dragon"
}

###

### Edit taxonomy
GET {{host}}/{{locale}}/spa/taxonomies/1/edit?type=category
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### Update taxonomy
PATCH {{host}}/{{locale}}/spa/taxonomies/25
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "translations": {
    "en": {
      "title": "EN title",
      "description": "EN description"
    },
    "ar": {
      "title": "العنوان",
      "description": "الوصف"
    },
    "tr": {
      "title": "TR title",
      "description": "TR description1"
    },
    "type": "category",
    "icon": "f641 fas fa-ad",
    "parentId": 1
  }
}

###

### delete taxonomy
DELETE {{host}}/{{locale}}/spa/taxonomies/7
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
