################## USERS ##################
# Get all users
GET {{host}}/{{locale}}/spa/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### create user
GET {{host}}/{{locale}}/spa/users/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### Store
POST {{host}}/{{locale}}/spa/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "first": "twewwdst",
  "last": "a",
  "gender": "1",
  "email": "taewswwt@test.test",
  "password": "secret test",
  "username": "w",
  "status": 1,
  "role": "super",
  "country_id": "1",
  "region_id": "1",
  "city_id": "1",
  "name": "nametest",
  "address1": "address1",
  "address2": "address2",
  "emails": {
    "1": "test1@test.test",
    "2": "test2@test.test"
  },
  "phones": {
    "home": "05382910485",
    "work": "05319503825"
  }
}

###

### Edit user
GET {{host}}/{{locale}}/spa/users/7/edit
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

###THESE DON'T WORK YET
### Update user
PATCH {{host}}/{{locale}}/spa/users/7
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "first": "testfirst",
  "last": "testlast",
  "gender": "1",
  "email": "test@test.test",
  "username": "test",
  "status": 1,
  "country_id": "1",
  "region_id": "1",
  "city_id": "1",
  "name": "awd",
  "address1": "address12",
  "address2": "address23",
  "emails": {
    "1": "test1@test.test",
    "2": "test2@test.test"
  },
  "phones": {
    "home": "05382910485",
    "work": "05319503825"
  }
}

###

### delete user
DELETE {{host}}/{{locale}}/spa/users/71
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
