################## OTP ##################

#### Get All Methods
GET {{host}}/{{locale}}/api/v1/otp/methods
Accept: application/json
Content-Type: application/json

####  Init validation for whatsapp or telegram. Required.
GET {{host}}/{{locale}}/api/v1/otp/init-validation?method=whatsapp
Accept: application/json
Content-Type: application/json


#### Check/Validation. [`reference`]. Required.
GET {{host}}/{{locale}}/api/v1/otp/check-validation/{{otpReference}}
Accept: application/json
Content-Type: application/json


#### SMS Send
POST {{host}}/{{locale}}/api/v1/otp/sms-send
Accept: application/json
Content-Type: application/json

{
    "phone_country_code": "90",
    "phone_number": "5070326662"
}

#### SMS Validation Code
POST {{host}}/{{locale}}/api/v1/otp/sms-validate
Accept: application/json
Content-Type: application/json

{
    "phone_country_code": "90",
    "phone_number": "5070326662",
    "code": "964291",
    "reference": "{{otpReference}}"
}

### countries with flags
GET {{host}}/{{locale}}/api/v1/countries?all=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
