################## ADDRESS ##################
### addresses index
GET {{host}}/{{locale}}/api/v1/profile/addresses
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### addresses create
GET {{host}}/{{locale}}/api/v1/profile/addresses/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "latitude": 40.8489891,
    "longitude": 29.1192525
}

### addresses store
POST {{host}}/{{locale}}/api/v1/profile/addresses
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "kind": "2",
    "region_id": 1,
    "city_id": 1,
    "alias": "My Home",
    "address1": "My Home explained",
    "name": "Home",
    "region_id": "15",
    "city_id": "15",
    "address1": "Şişli merkiz sk NO: 14 / B  23231",
    "latitude": 40.8489891,
    "longitude": 29.1192525,
    "notes": "The elevator is not working lol"
}

### addresses store
POST {{host}}/{{locale}}/api/v1/profile/addresses/change-selected-address
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "latitude": 40.8489891,
    "longitude": 29.1192525
}

### delete user
DELETE {{host}}/{{locale}}/api/v1/profile/addresses/4
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
