### Restaurant Show
GET {{host}}/{{locale}}/api/v1/restaurants/{{restaurantId}}
Accept: application/json
Content-Type: application/json

### Restaurant filter create
GET {{host}}/{{locale}}/api/v1/restaurants/filter
Accept: application/json
Content-Type: application/json


### Restaurant filter create
### delivery_type = tiptop or restaurant
### sort = restaurants_rating or by_distance or (samrt_sorting as default)
POST {{host}}/{{locale}}/api/v1/restaurants
Accept: application/json
Content-Type: application/json

{
    "delivery_type": null,
    "minimum_order": null,
    "min_rating": null,
    "categories": [],
    "sort": "by_distance",
    "latitude": 41.10184151967425,
    "longitude": 28.986855325376577,
    "selected_address_id": null
}
