### Restaurant Show
GET {{host}}/{{locale}}/api/v1/restaurants/{{restaurantId}}
Accept: application/json
Content-Type: application/json

### Restaurant filter create
GET {{host}}/{{locale}}/api/v1/restaurants/filter
Accept: application/json
Content-Type: application/json

