### Restaurant Show
GET {{host}}/{{locale}}/api/v1/restaurants/{{restaurantId}}
Accept: application/json
Content-Type: application/json

### Restaurant filter create
GET {{host}}/{{locale}}/api/v1/restaurants/filter
Accept: application/json
Content-Type: application/json


### Restaurant filter create
### delivery_type = tiptop or restaurant
### sort = restaurants_rating or by_distance or (samrt_sorting as default)
POST {{host}}/{{locale}}/api/v1/restaurants/filter
Accept: application/json
Content-Type: application/json

{
    "delivery_type": "tiptop",
    "min_rating": 4,
    "categories": [
        3,
        4,
        5
    ],
    "minimum_order": 500,
    "sort": "restaurants_rating"
}
