################## Order/Checkout ##################
### Get checkout data
GET {{host}}/{{locale}}/api/v1/orders/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "chain_id": "1",
    "branch_id": "1"
}

### Previous orders index
GET {{host}}/{{locale}}/api/v1/orders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Store checkout data.
POST {{host}}/{{locale}}/api/v1/orders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
#Required fields [chain_id, branch_id, cart_id, payment_method_id, address_id].

{
    "chain_id": "1",
    "branch_id": "1",
    "cart_id": "2",
    "payment_method_id": "1",
    "address_id": "1",
    "notes": null
}

### Order delete
POST {{host}}/{{locale}}/api/v1/orders/1/delete
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Order create rate.
GET {{host}}/{{locale}}/api/v1/orders/1/rate
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Order store rate.
POST {{host}}/{{locale}}/api/v1/orders/1/rate
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "branch_rating_value": 3.2,
    "grocery_issue_id": 28,
    "driver_rating_value": 3.2,
    "food_rating_factors": {
        "has_good_food_quality_rating": true,
        "has_good_packaging_quality_rating": false,
        "has_good_order_accuracy_rating": null
    },
    "comment": "This is not what I ordered!"
}
