################## Pages ##################

# blog - index
GET {{host}}/{{locale}}/api/v1/blog
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

# blog - show
GET {{host}}/{{locale}}/api/v1/blog/5
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### faq - index
GET {{host}}/{{locale}}/api/v1/faq
Accept: application/json
Content-Type: application/json


### faq - index
GET {{host}}/{{locale}}/api/v1/support
Accept: application/json
Content-Type: application/json

### about - index
GET {{host}}/{{locale}}/api/v1/about-us
Accept: application/json
Content-Type: application/json

### privacy - index
GET {{host}}/{{locale}}/api/v1/privacy-policy
Accept: application/json
Content-Type: application/json

### terms - index
GET {{host}}/{{locale}}/api/v1/terms-and-conditions
Accept: application/json
Content-Type: application/json
