################## PRODUCT ##################
### products index
GET {{host}}/{{locale}}/api/v1/categories/2/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### product show
GET {{host}}/{{locale}}/api/v1/products/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### search products
GET {{host}}/{{locale}}/api/v1/search/products?q=appleeee
Accept: application/json
Content-Type: application/json


###  remove or add product
POST {{host}}/{{locale}}/api/v1/carts/{cart}/products/adjust-quantity
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "product_id": "5",
    "chain_id": "1",
    "branch_id": "3",
    "is_adding": "1",
    "status": "0"
}

###  clear cart
POST {{host}}/{{locale}}/api/v1/carts/{cart}/delete
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

