################## Misc ##################

### boot
GET {{host}}/{{locale}}/api/v1/boot
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "platform": "iOS",
    "build_number": 251
}

### home
GET {{host}}/{{locale}}/api/v1/home
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "latitude": 36.20339842006327,
    "longitude": 44.00734072932359,
    "channel": "grocery",
    "selected_address_id": 1
}

### products
GET {{host}}/{{locale}}/api/v1/categories/2/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### faqs
GET {{host}}/{{locale}}/api/v1/faqs
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### faq
GET {{host}}/{{locale}}/api/v1/faqs/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### privacy
GET {{host}}/{{locale}}/api/v1/privacy
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### log
POST {{host}}/{{locale}}/api/v1/logs/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "data": "idk"
}

### countries with flags
GET {{host}}/{{locale}}/api/v1/countries?all=true
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

