################## AUTH ##################
POST {{host}}/{{locale}}/api/v1/login
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "demo@trytiptop.app",
    "password": "secret"
}

### log out
POST {{host}}/{{locale}}/api/v1/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
