################## OTP ##################

#### Get All Methods
GET {{host}}/{{locale}}/api/v1/otp/methods
Accept: application/json
Content-Type: application/json

####  Init validation for whatsapp or telegram. Required.
GET {{host}}/{{locale}}/api/v1/otp/init-validation?method=whatsapp
Accept: application/json
Content-Type: application/json


#### Check/Validation. [`reference`]. Required.
GET {{host}}/{{locale}}/api/v1/otp/check-validation/{{otpReference}}
Accept: application/json
Content-Type: application/json


#### SMS Send
POST {{host}}/{{locale}}/api/v1/otp/sms-send
Accept: application/json
Content-Type: application/json

{
    "country_code": "TR",
    "phone_number": "+905395534325"
}

#### SMS Validation Code
POST {{host}}/{{locale}}/api/v1/otp/sms-validate
Accept: application/json
Content-Type: application/json

{
    "country_code": "TR",
    "phone_country_code": "+90",
    "phone_number": "5395534325",
    "code": "480468",
    "reference": "b830bdc2288265ff945ec43592742428f043dd13"
}
