################## PRODUCT ##################
### products index
GET {{host}}/{{locale}}/api/v1/categories/2/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### product show
GET {{host}}/{{locale}}/api/v1/products/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}



###  remove or add product
POST {{host}}/{{locale}}/api/v1/carts/{{cartId}}/products/adjust-quantity
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "product_id_in_cart": {{productIdInCart}},
    "product_id": {{productId}},
    "chain_id": {{chainId}},
    "branch_id": "{{branchId}}",
    "is_adding": true,
    "status": 0,
    "selected_options": [
        {
            "id": 12,
            "selection_ids": [952, 1013, 1023]
        },
        {
            "id": 16,
            "selection_ids": [20,21]
        }
    ]
}

###  clear cart
POST {{host}}/{{locale}}/api/v1/carts/{{cart}}/delete
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "chain_id": {{chainId}},
    "branch_id": {{branchId}}
}
