################## SETTINGS ##################
GET {{host}}/{{locale}}/api/v1/settings
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Defaults
GET {{host}}/{{locale}}/api/v1/settings/defaults
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Edit profile
POST {{host}}/{{locale}}/api/v1/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "admin",
  "email": "info@example.com",
  "password": "secret1234",
  "phone_number": "555888",
  "phone_country_code": "",
  "dob": "1994-06-16",
  "gender": "Male",
  "locale": "en"
}



### Logout
POST {{host}}/{{locale}}/api/v1/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
