################## Order/Checkout ##################
### Restaurant orders index
GET {{host}}/{{locale}}/api/restaurants/v1/restaurants/1/orders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

#1 cancelled
#2 draft
#3 new
#10 preparing
#20 delivered
#25 scheduled

{
    "status": "1"
}

### Order delete
POST {{host}}/{{locale}}/api/restaurants/v1/orders/1/delete
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
