################## Restaurant ##################
### restaurants edit
GET {{host}}/{{locale}}/api/restaurants/v1/restaurants/473/edit
Accept: application/json
Content-Type: application/json

### restaurants update
PUT {{host}}/{{locale}}/api/restaurants/v1/restaurants/445
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "delivery_time": "6-7",
    "minimum_order": 21,
    "delivery_fee": 4,
    "covered_area_diameter": 500,
    "phone_number": "7501234123"
}

### restaurants toggle activity
POST {{host}}/{{locale}}/api/restaurants/v1/restaurants/445/toggle-activity
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### restaurants categories
GET {{host}}/{{locale}}/api/restaurants/v1/restaurants/412/categories
Accept: application/json
Content-Type: application/json


