################## COUNTRIES ##################
# Get all countries
GET {{host}}/{{locale}}/api/v1/countries
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### create country
GET {{host}}/{{locale}}/api/v1/countries/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

### Store
POST {{host}}/{{locale}}/api/v1/countries
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currency_id": 4,
  "language_id": 2,
  "timezone_id": 332,
  "english_name": "TEST",
  "alpha2_code": "TE",
  "alpha3_code": "TES",
  "numeric_code": 4,
  "phone_code": 92,
  "status": 1,
  "translations": {
    "en": {
      "name": "name",
      "slug": "slug"
    },
    "ar": {
      "name": "سوسو",
      "slug": "بابا"
    }
  }
}

###

### Edit country
GET {{host}}/{{locale}}/api/v1/countries/255/edit
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
###

###THESE DON'T WORK YET
### Update country
PATCH {{host}}/{{locale}}/api/v1/countries/256
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currency_id": 1,
  "language_id": 4,
  "timezone_id": 13,
  "english_name": "TEST2",
  "alpha2_code": "T2",
  "alpha3_code": "TE2",
  "numeric_code": 1,
  "phone_code": 97,
  "status": 1,
  "translations": {
    "en": {
      "name": "name2",
      "slug": "slug2"
    },
    "ar": {
      "name": "سوسو2",
      "slug": "بابا2"
    }
  }
}

###

### delete country
DELETE {{host}}/{{locale}}/api/v1/countries/257
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
