################## AUTHENTICATION RELATED ##################
### Login
POST {{host}}/{{locale}}/api/v1/login
Accept: application/json
Content-Type: application/json

{
    "email": "demo@trytiptop.app",
    "password": "secret"
}

### Register
POST {{host}}/{{locale}}/api/v1/register
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
#< ./data/example.json

{
    "name": "John Doe",
    "email": "example@domain.com",
    "password": "secret1234",
    "phone_number": "555",
    "phone_country_code": "",
    "dob": 662688000,
    "gender": "",
    "locale": ""
}


### Reset Password
POST {{host}}/{{locale}}/api/v1/password/reset
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "email": "info@multicaret.com"
}

### Languages
GET {{host}}/{{locale}}/api/v1/languages
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Timezones
GET {{host}}/{{locale}}/api/v1/timezones
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Currencies
GET {{host}}/{{locale}}/api/v1/currencies
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

################## LOGISTICS ##################
### Countries
GET {{host}}/{{locale}}/api/v1/countries
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Regions (225 is the ID of Turkey)
GET {{host}}/{{locale}}/api/v1/countries/225/regions
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Cities (225 is the ID of Turkey, 34 is the ID of Istanbul)
GET {{host}}/{{locale}}/api/v1/countries/225/regions/34/cities
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### Get Supported/Enabled locales
GET {{host}}/{{locale}}/api/v1/settings/locales
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

