################## TIMEZONES ##################
# Get all available Timezones
GET {{host}}/{{locale}}/api/v1/timezones
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

### create timezone
GET {{host}}/{{locale}}/api/v1/timezones/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

### Store
POST {{host}}/{{locale}}/api/v1/timezones
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "timezone name",
    "utc_offset": 2,
    "dst_offset": -5
}

###

### Edit timezone
GET {{host}}/{{locale}}/api/v1/timezones/420/edit
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###


### Update timezone
PATCH {{host}}/{{locale}}/api/v1/timezones/420
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "timezone name2",
    "utc_offset": -2,
    "dst_offset": 7
}

###

### delete timezone
DELETE {{host}}/{{locale}}/api/v1/timezones/419
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###
