################## Misc ##################

### boot
GET {{host}}/{{locale}}/api/restaurants/v1/boot
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{tokenRestaurant}}

{
    "platform": "iOS",
    "build_number": 251
}

### log
POST {{host}}/{{locale}}/api/restaurants/v1/logs/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{tokenRestaurant}}

{
    "data": "idk"
}
