################## Restaurant ##################
### restaurants edit
GET {{host}}/{{locale}}/api/restaurants/v1/restaurants/473/edit
Accept: application/json
Content-Type: application/json

### restaurants update
POST {{host}}/{{locale}}/api/restaurants/v1/restaurants/445
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{tokenRestaurant}}

{
    "delivery_time": "6-7",
    "minimum_order": 21,
    "delivery_fee": 4,
    "covered_area_diameter": 500,
    "phone_number": "7501234123"
}

### restaurants toggle activity
POST {{host}}/{{locale}}/api/restaurants/v1/restaurants/445/toggle-status
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{tokenRestaurant}}

{
    "status": true
}

### restaurants categories
GET {{host}}/{{locale}}/api/restaurants/v1/restaurants/412/categories
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{tokenRestaurant}}

### products adjust price
POST {{host}}/{{locale}}/api/restaurants/v1/restaurants/473/products/37462
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{tokenRestaurant}}

{
    "price": 37
}

### products toggle status
POST {{host}}/{{locale}}/api/restaurants/v1/restaurants/410/products/45815/toggle-status
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{tokenRestaurant}}

{
    "status": true
}
